name: Nepozorni project CI

on:
  push:
    branches: [main, release, development]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Set Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install libraries
        run: |
              pip install -U Pillow opencv-python pytest ultralytics

      - name: Run tests
        run: |
          pytest --junitxml=results.xml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results.xml

      - name: Zip entire repo
        run: |
          zip -r nepozorni.zip . -x '*.git*' -x 'nepozorni.zip' -x 'results.xml'

      - name: Upload zipped repo
        uses: actions/upload-artifact@v4
        with:
          name: zipped-repo
          path: nepozorni.zip